package main.java.com.virtualpairprogrammers;
//Was created for us

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import javax.rmi.CORBA.Util;

/*
 * A wrapper for an input file containing a list of what we think are 'boring' words
 * THis list was generated by running a word count across all of VirtualPairProgrammers subtitle files
 * Words that appear in every course (we think) must be 'boring' - they do not have relevance to one specific course
 * The list of words is 'small data' - can safely be loaded into the drivers JVM, no need to distribute the data 
 */

public class Utils {

	public static Set<String> borings = new HashSet<String>();
	
	static {
		//in the video instructor says 'change class name', we can ignore that. Class name should be Util
		InputStream is = Util.class.getResourceAsStream("subtitles/boringwords.txt");
		BufferedReader br = new BufferedReader(new InputStreamReader(is));
		br.lines().forEach(borings::add);
	}
	
	//Returns true if we think the word is boring - not a keyword for a training course
	public static boolean isBoring(String word) {
		return borings.contains(word);
	}
	
	//Convenience method for more readable client code
	public static boolean isNotBoring(String word) {
		return !isBoring(word); //again, this means is NOT boring
	}
}
